export const caribbeanPhrases = [
  // Personal
  "Life is hard, but harder is being born in La Guajira.",
  "I did this for my wife, who inspires me every day to be a better person, and for my entire family, whom I love.",
  "With all there is to see nowadays, it’s better to be blind.",

  // Coastal sayings
  "Ajá, life is meant to be lived joyfully.",
  "With patience and calm, you can climb even the tallest palm.",
  "If you fall, get back up with greater strength.",
  "Never stop enjoying life, because to enjoy is to live.",
  "The Caribbean breeze refreshes even the tired soul.",
  "An accordion sounds more beautiful when it’s played with the heart.",
  "On the coast, we cry while dancing and laugh while singing.",
  "He who hasn’t sweated in a party hasn’t truly lived.",
  "In the Caribbean, happiness is the law of life.",
  "The sea teaches that everything flows and everything returns.",
  "A smile is the best souvenir from the Caribbean.",
  "Better a short but joyful life than a long and bitter one.",

  // Diomedes Díaz quotes
  "I will never get tired of singing to my people.",
  "Ay hombe, live life with joy.",
  "Thanks to my people for so much love.",
  "Vallenato is the music that gave me life.",
  "A man without friends is like an accordion without a box.",
  "He never dies who leaves a legacy in the hearts of the people.",
  "Whoever doesn’t live to serve, doesn’t serve to live.",
  "My people’s love is the crown I will always wear.",
  "I was born to sing, and singing is how I’ll live forever.",

  // Motivational
  "Believe in yourself and anything is possible.",
  "Discipline beats talent when talent doesn’t work hard.",
  "Every day is a new chance to change your life.",
  "The harder the battle, the sweeter the victory.",
  "Dream big, start small, act now.",
  "Push yourself, because no one else is going to do it for you.",
  "Success is the sum of small efforts repeated day in and day out.",
  "Don’t stop when you’re tired, stop when you’re done.",
  "Great things never come from comfort zones.",
  "Your only limit is your mind.",
  "Do something today that your future self will thank you for.",
  "Fall seven times and stand up eight.",
  "Small steps every day lead to big results.",
  "Hard work beats luck when luck doesn’t show up.",
  "Be stronger than your excuses.",
  "When you feel like quitting, remember why you started.",
  "Progress is progress, no matter how small.",
  "Turn your dreams into goals, and your goals into reality.",
  "Success doesn’t come to you, you go to it.",
  "Winners are not people who never fail, but people who never quit.",
  "Doubt kills more dreams than failure ever will.",
  "Keep going, because everything you need will come at the right time.",
  "If it doesn’t challenge you, it won’t change you.",
  "Success begins with the decision to try.",
  "Your time is now, not tomorrow.",
  "Pain is temporary, pride is forever.",
  "Don’t wish for it, work for it.",
  "You are stronger than you think.",
  "Stay positive, work hard, make it happen.",
  "Believe you can and you’re halfway there.",
  "The best view comes after the hardest climb.",
  "Big journeys begin with small steps.",
  "Consistency is what transforms average into excellence.",
  "Strength grows in the moments you think you can’t go on but keep going anyway.",
  "Don’t let yesterday take too much of today.",
  "Act as if what you do makes a difference. It does.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "Keep your face always toward the sunshine, and shadows will fall behind you.",
  "Great things take time, don’t rush them.",
  "The key to success is to focus on goals, not obstacles.",
  "Difficult roads often lead to beautiful destinations.",
  "Don’t be afraid to start over, it’s a chance to build something better.",
  "Your potential is endless.",
  "Make today count, you’ll never get it back.",
  "Stay hungry, stay foolish."
];
